sudo: enabled
install:
    apt update -y 
    apt upgrade -y 
    apt install csh gfortran byobu automake mpich m4 -y &&\
    apt install libhdf5-mpich-dev libpng-dev libnetcdf-dev -y &&\
    apt install libnetcdff-dev ncl-ncarg libjasper-dev -y &&\
    apt install libc-bin localepurge build-essential -y &&\
    apt-get install hdf5* netcdf* ncl* -y
    
script:
after_script:  
branches:
  only:
    - source
env:
 global:
   - GH_REF: 
  
