sudo: enabled

language: node_js
node_js:
  - '7.5.0'
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - npm install
  - npm install gulp
script: npm run build
after_script:  
  - cd ./public
  - echo "rki.moe" > CNAME
  - git init
  - git config user.name "Mikubill"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/Mikubill/rkicore.git
  
