os: linux
dist: xenial
sudo: required
install:
   - sudo apt-get update 
   - sudo apt-get upgrade -y  
   - sudo apt-get install wget hdf5* netcdf* ncl* libc-bin localepurge libtool build-essential libnetcdff-dev ncl-ncarg libjasper-dev csh gfortran byobu automake libhdf5-mpich-dev libpng-dev libnetcdf-dev mpich m4 -y
   - mkdir ncl
   - wget https://x.ahx.jp/e9/8e3bf21906ef36c7a0539117db0ba29bb7a670.gz
   - mv 8e3bf21906ef36c7a0539117db0ba29bb7a670.gz ncl/
   - wget https://x.ahx.jp/b0/51a5ac1cc2fc4d32eb7b1bad2550d55a91a1d3
   - mv 51a5ac1cc2fc4d32eb7b1bad2550d55a91a1d3 tc.exe
   - chmod +x tc.exe
   - cd ncl
   - tar zxvf 8e3bf21906ef36c7a0539117db0ba29bb7a670.gz
   - cd ..
   - wget https://x.ahx.jp/75/7a6c2580c6e37781146fe01e9e0356a1928570.bat
   - mv 7a6c2580c6e37781146fe01e9e0356a1928570.bat run.sh
   - chmod +x run.sh
   - mkdir libiconv
   - cd libiconv 
   - wget https://x.ahx.jp/7a/f3149fa7c4bd1d3a36a30f02e95a0ebfd6b18f.gz
   - tar zxvf f3149fa7c4bd1d3a36a30f02e95a0ebfd6b18f.gz
   - cd libiconv-1.15/
   - ./configure --prefix=/usr
   - make
   - sudo make install
   - cd ../../
script: 
   - bash run.sh
after_script:  ls
  
