sudo: required

services:
  - docker
  
before_install:
  - docker pull mikubill/wrf-wps:3.9-em_real
  - docker run -d -t --name "wrfrun" mikubill/wrf-wps:3.9-em_real

script:
  - docker ps
  - docker exec "wrfrun" bash -c "ls /root/WRFV3"
  - docker exec "wrfrun" bash -c "mkdir /root/wrfrun "
  - docker cp `pwd`/1_kf_base wrfrun:/root/wrfrun
  - docker cp `pwd`/data_origin wrfrun:/root/wrfrun
  - docker exec "wrfrun" bash -c "ln -s /root/WRFV3/main/* /root/wrfrun/"
  - docker exec "wrfrun" bash -c "ln -s /root/WRFV3/run/* /root/wrfrun/"
  - docker exec "wrfrun" bash -c "/root/wrfrun/real.exe"
  - docker exec "wrfrun" bash -c "/root/wrfrun/wrf.exe"
  
