sudo: required

services:
  - docker
  
before_install:
  - docker pull mikubill/wrf-wps:3.9-em_real
  - docker run -d -t --name "wrfrun" mikubill/wrf-wps:3.9-em_real

script:
  - cd `pwd`/data_origin/
  - mv met_em.d01.2017-07-28_12_00_00.nc met_em.d01.2017-07-28_12\:00\:00.nc
  - mv met_em.d01.2017-07-28_18_00_00.nc met_em.d01.2017-07-28_18\:00\:00.nc
  - mv met_em.d01.2017-07-29_00_00_00.nc met_em.d01.2017-07-29_00\:00\:00.nc
  - mv met_em.d01.2017-07-29_06_00_00.nc met_em.d01.2017-07-29_06\:00\:00.nc
  - mv met_em.d01.2017-07-29_12_00_00.nc met_em.d01.2017-07-29_12\:00\:00.nc
  - mv met_em.d01.2017-07-29_18_00_00.nc met_em.d01.2017-07-29_18\:00\:00.nc
  - mv met_em.d01.2017-07-30_00_00_00.nc met_em.d01.2017-07-30_00\:00\:00.nc
  - mv met_em.d01.2017-07-30_06_00_00.nc met_em.d01.2017-07-30_06\:00\:00.nc
  - mv met_em.d02.2017-07-28_12_00_00.nc met_em.d02.2017-07-28_12\:00\:00.nc
  - mv met_em.d02.2017-07-28_18_00_00.nc met_em.d02.2017-07-28_18\:00\:00.nc
  - mv met_em.d02.2017-07-29_00_00_00.nc met_em.d02.2017-07-29_00\:00\:00.nc
  - mv met_em.d02.2017-07-29_06_00_00.nc met_em.d02.2017-07-29_06\:00\:00.nc
  - mv met_em.d02.2017-07-29_12_00_00.nc met_em.d02.2017-07-29_12\:00\:00.nc
  - mv met_em.d02.2017-07-29_18_00_00.nc met_em.d02.2017-07-29_18\:00\:00.nc
  - mv met_em.d02.2017-07-30_00_00_00.nc met_em.d02.2017-07-30_00\:00\:00.nc
  - mv met_em.d02.2017-07-30_06_00_00.nc met_em.d02.2017-07-30_06\:00\:00.nc
  - cd ..
  - docker ps
  - docker exec "wrfrun" bash -c "ls /root/WRFV3"
  - docker exec "wrfrun" bash -c "mkdir /root/wrfrun "
  - docker cp `pwd`/1_kf_base wrfrun:/root/wrfrun
  - docker cp `pwd`/data_origin wrfrun:/root/wrfrun
  - docker exec "wrfrun" bash -c "ln -s -b /root/WRFV3/main/* /root/wrfrun/"
  - docker exec "wrfrun" bash -c "ln -s -b /root/WRFV3/run/* /root/wrfrun/"
  - docker exec "wrfrun" bash -c "mv /root/wrfrun/1_kf_base/* /root/wrfrun"
  - docker exec "wrfrun" bash -c "mv /root/wrfrun/data_origin/* /root/wrfrun"
  - docker exec "wrfrun" bash -c "cd /root/wrfrun && ./real.exe | tail -f --pid=$(ps -ef | grep 'real.exe' | awk '{print $2}') rsl.out.0000"
  - docker exec "wrfrun" bash -c "cd /root/wrfrun && ./wrf.exe | tail -f --pid=$(ps -ef | grep 'wrf.exe' | awk '{print $2}') rsl.out.0000"
  - docker exec "wrfrun" bash -c "ls -lah /root/wrfrun/"
